name: Continuous Deployment (az not azd)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/cd
      
permissions:
  id-token: write
  contents: read

jobs:
  continuous_deployment_with_az:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:          
      - name: "Check versions"
        run: |
          azd version
          az --version
          python --version
          
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd 
          ls

      - name: 'git clone and cd'
        run: |
          git clone https://github.com/rukasakurai/jp-azureopenai-samples
          cd jp-azureopenai-samples/5.internal-document-search/src/backend
          pwd
          ls
          
      - name: Setup Python 3.x 
        uses: actions/setup-python@v1
        with:
          python-version: 3.x        
          
      - name: 'Install dependencies'
        shell: bash
        run: |
          which python
          which python3.11
          echo $LD_LIBRARY_PATH
          ls /usr/lib
          export LD_LIBRARY_PATH=/usr/lib
          echo $LD_LIBRARY_PATH
          python -m pip install --upgrade pip
          pip install -r requirements.txt
   
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: '.'
