name: Greeting on variable day

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    env:
      Greeting: Hello
      TEST_VAR: ${{ vars.TEST_VAR }}
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: "Check azd version"
        run: azd version
      - name: "Check variables"
        run: echo "TEST_VAR is $TEST_VAR"
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd 
      - name: 'Run Azure Developer CLI commands'
        run: |
          azd version
          pwd
          ls
          git clone https://github.com/rukasakurai/jp-azureopenai-samples
          ls
          cd jp-azureopenai-samples/5.internal-document-search/src
          pwd
          ls
          export AZURE_PRINCIPAL_ID=${{ secrets.AZURE_PRINCIPAL_ID }}
          azd deploy
          pwd 
