name: Greeting on variable day

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    env:
      Greeting: Hello
      TEST_VAR: ${{ vars.TEST_VAR }}
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: "Check azd version"
        run: azd version
      - name: "Check variables"
        run: echo "TEST_VAR is $TEST_VAR"
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true
      - name: 'Run Azure CLI commands'
        run: |
          az account show
          az group list
          pwd 
